apiVersion: v1
kind: Namespace
metadata:
  name: falco

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: falco

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco
rules:
  # Falco uses the Kubernetes audit log to detect anomalous behavior.
  # This cluster role allows Falco to read events and metadata.
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - namespaces
      - nodes
      - serviceaccounts
      - endpoints
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco
subjects:
  - kind: ServiceAccount
    name: falco
    namespace: falco
